services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
    depends_on:
      - test-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@test-db:5432/test_db
      - TESTING=True
    command: pytest -v tests

  test-db:
    image: postgres:15
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"

volumes:
  postgres_test_data:
