"""add fields to user model

Revision ID: 98ae6a903c6b
Revises: ba12c66cce69
Create Date: 2025-03-22 18:50:23.605837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ae6a903c6b'
down_revision: Union[str, None] = 'ba12c66cce69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # create type userroles
    op.execute('CREATE TYPE userroles AS ENUM (\'admin\', \'user\')')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('salt', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.Enum('admin', 'user', name='userroles')), nullable=False, server_default="{user}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
    op.execute('DROP TYPE userroles')
